# Generated by Django 2.2.16 on 2022-03-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalotprequests',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otprequests',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
